# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#
# settings_reset: use when left and right side are switched on different boards
# ---
# board: [ "nice_nano" ]
# shield: [ "foxyduck", "sosuke", "sosuke_dongle" ]

include:
  - board: xiao_ble//zmk
    shield: zukuma_dongle rgbled_adapter #dongle_display 
  # - board: xiao_ble
  #   shield: zukuma
  #   shield: settings_reset
  # - board: nice_nano
  #   shield: foxyduck
  #   shield: altiplano
  #   shield: sosuke
  #   shield: settings_reset